function swmm_init_storage(ffile_model,init_depth)
%% function sets a constant initial depth to all of the storage elements contained in a SWMM INP file

storage_elements = swmm_class(ffile_model,'storage');
% init_depth = 0.2;

for i2 = 1:height(storage_elements)
    storage_params(i2) = swmm_param('storage',...
        storage_elements.Properties.RowNames{i2},...
        storage_elements.Name{i2},...
        'InitDepth',...
        storage_elements(i2,'InitDepth').Variables);
    
    storage_params(i2).new_val = init_depth;
end

fprintf(['setting initial depth of STORAGE elements to %2.2fm\n'],init_depth)
swmm_elements(ffile_model,...
    {storage_params.class},...
    {storage_params.attribute},...
    {storage_params.id},...
    [storage_params.new_val]);